import React, { Suspense } from "react";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: "0px" }} className={inter.className}>
        {/* <Suspense fallback={<h1>Loading...</h1>}> */}
          {children}
        {/* </Suspense> */}
      </body>
    </html>
  );
}
