version: '3.8'
services:
  mysql_image:
    image: mysql:latest
    command:
      [
        'mysqld',
        '--default-authentication-plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    ports:
      - 8083:3306
    networks:
      - main
    environment:
      MYSQL_DATABASE: hestia
      MYSQL_ROOT_PASSWORD: manasou
    volumes:
      - mysql_vol:/var/lib/mysql

  # waitt:
  #   image: ubuntu:latest
  #   command: [ "bash", "sleep 20" ]
  #   entrypoint: [ "bash", "echo", "'done'" ]
  #   profiles:
  #     - first_batch
  #   depends_on:
  #     - mysql_image

  api:
    build: ./api/
    env_file:
      - ./api/.env.sample
    ports:
      - 8081:8081
    profiles:
      - first_batch
    networks:
      - main
    depends_on:
      - mysql_image

  front:
    build: ./front/
    expose:
      - 8082
    profiles:
      - second_batch
    networks:
      - main
    depends_on:
      - api

  nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 8000:80
    profiles:
      - second_batch
    networks:
      - main
    depends_on:
      - front
volumes:
  mysql_vol:
networks:
  main:
