version: '3'
services:
  mysql_image:
    image: mysql:latest
    command:
      [
        'mysqld',
        '--default-authentication-plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    ports:
      - 8083:3306
    networks:
      - main
    environment:
      MYSQL_DATABASE: hestia
      MYSQL_ROOT_PASSWORD: manasou
    volumes:
      - mysql_vol:/var/lib/mysql

  waitt:
    image: ubuntu:latest
    command: [ "bash", "sleep 20" ]
    entrypoint: [ "bash", "echo", "'done'" ]
    depends_on:
      - mysql_image

  api:
    build: ./api/
    # entrypoint: ./api/entrypoint.sh
    env_file:
      - ./api/.env
    expose:
      - 8081
    networks:
      - main
    depends_on:
      - waitt

  front:
    build: ./front/
    expose:
      - 8082
    networks:
      - main
    depends_on:
      - api

  nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 8000:80
    networks:
      - main
    depends_on:
      - api
volumes:
  mysql_vol:
networks:
  main:
